### ISSUE TITLE
🐛 Resposta de sucesso sendo retornada no parâmetro `error`

### ISSUE THREAD

**Issue by tuliospuri** [gerencianet/gn-api-sdk-go-pix#1]
Bom dia.

Ao criar uma cobrança o retorno da API Pix é 201 (Created). O SDK está avaliando o status 200 (Ok) e isto está fazendo com que a resposta de sucesso seja retornada no parâmetro error do método `request`. 

Referência: 
https://github.com/gerencianet/gn-api-sdk-go-pix/blob/main/gerencianet/requester.go#L93

**Comment by matheus-rodriguesGN** [comment]
Fixed!
